/**
  *  \file           ICM20948.h
  *  \brief          Header file ICM20948 interface.
  *
  *  \author         Davide Marzorati
  */

/*******************************************************************************
 * Copyright (c) 2021 Marzorati Davide
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge,
 * publish, distribute, sublicense, and/or sell copies of the Software,
 * and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
 * AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
*******************************************************************************/

#ifndef __ICM20948_H__
    #define __ICM20948_H__
    
    #ifdef __cpluscplus 
        extern "C" {
    #endif
    
    #include "cytypes.h"
    #include "cyfitter.h"
    
    /***********************************
    *           API Constants          *
    ************************************/
    
    /**
     *  \brief          No error generated by API call.
     */
    #define ICM20948_OK             0
    
    /**
     *  \brief          I2C communication error occurred during API execution.
     */
    #define ICM20948_I2C_ERR        1
    
    /**
     *  \brief          Device not found on API bus error.
     */
    #define ICM20948_DEV_NOT_FOUND  2
    
    /**
     *  \brief          Parameter error when calling API.
     */
    #define ICM20948_CONF_ERR       3
    
    
    uint8_t ICM20948_ReadWhoAmI(uint8_t* who_am_i);
    
    #ifdef __cpluscplus
        }
    #endif
    
#endif
/* [] END OF FILE */
